"""add studio settings

Revision ID: 0003_add_studio_settings
Revises: 0002_add_is_admin_column
Create Date: 2026-06-18 14:51:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_add_studio_settings'
down_revision = '0002_add_is_admin_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('work_hours_start', sa.Time(), nullable=True),
    sa.Column('work_hours_end', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studio_settings')
    # ### end Alembic commands ###